### ISSUE TITLE
DEFECT: Images on the marketplace page do not show

### ISSUE THREAD

**Issue by xuhdev** [zbeekman/EditorConfig-Action#26]
**Describe the bug**
Images on the [marketplace page](https://github.com/marketplace/actions/editorconfig-action) do not display. Seems like the URLs are incorrect.

**Comment by zbeekman** [comment]
Yes, thanks for pointing this out. I'll update it soon. Cheers.

**Comment by zbeekman** [comment]
Fixed in e4e524f711c41d143be371eec0070a795073a98e
